export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";

/*Add order to cart*/
export const ADD_ORDER_TO_CART_REQUEST = "ADD_ORDER_TO_CART_REQUEST";
export const ADD_ORDER_TO_CART_SUCCESS = "ADD_ORDER_TO_CART_SUCCESS";
export const ADD_ORDER_TO_CART_ERROR = "ADD_ORDER_TO_CART_ERROR";
