export const REGISTER_USER_DATA_REQUEST = 'REGISTER_USER_DATA_REQUEST';
export const REGISTER_USER_DATA_SUCCESS = 'REGISTER_USER_DATA_SUCCESS';
export const REGISTER_USER_DATA_ERROR = 'REGISTER_USER_DATA_ERROR';
